version: '3.9'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app_network

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
